development: &development
  adapter: postgresql
  host: localhost
  database: bjond_pokitdok_dev
  encoding: unicode
  
test: &test
  adapter: postgresql
  host: localhost
  database: bjond_pokitdok_test
  encoding: unicode 