development: &development
  adapter: postgresql
  host: localhost
  database: bjondapp_dev
  encoding: unicode
  
test: &test
  adapter: postgresql
  host: localhost
  database: bjondapp_test
  encoding: unicode 